### PR TITLE
feat: extract financing to it's own table & fix: Finance vehicle menu

### LINKED ISSUE #30: Refactor: Split Finance Into Its Own DB Table
### The problem

the DB interactions of vehicles should be owned by core as many different resources likely need to interact with vehicles in DB. However, finance is a concept that should be owned by vehicleshop.

### Ideal solution

- The existing table for player owned vehicles is split, with a finance table storing finance data related to a vehicle
- the storage layer to interact with player owned vehicles is moved to core and exposed as exports to create a cleaner API for resources like vehicleshop to use

### Alternative solutions

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TonybynMp4**
## Description
Worked on #30, it shouldn't really cause any problem for backwards compat, maybe a migration would do the job?

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

File: migrate.sql [hunk 1]
```diff
@@ -0,0 +1,23 @@
+CREATE TABLE IF NOT EXISTS `vehicle_financing` (
+    `id` int(11) NOT NULL AUTO_INCREMENT,
```
Comment (Manason) [inline migrate.sql]: Shouldn't this id be a foreign key of the vehicle id itself? I wouldn't expect us to need to support multiple finance entries per vehicle

File: migrate.sql [hunk 2]
```diff
@@ -0,0 +1,23 @@
+CREATE TABLE IF NOT EXISTS `vehicle_financing` (
+    `id` int(11) NOT NULL AUTO_INCREMENT,
+    `citizenid` varchar(50) DEFAULT NULL,
```
Comment (Manason) [inline migrate.sql]: Do we need the citizenid? Could go through the vehicles table to inner join all vehicles associated to a citizenid with a finance entry.

File: migrate.sql [hunk 3]
```diff
@@ -0,0 +1,23 @@
+CREATE TABLE IF NOT EXISTS `vehicle_financing` (
+    `id` int(11) NOT NULL AUTO_INCREMENT,
+    `citizenid` varchar(50) DEFAULT NULL,
+    `plate` varchar(15) NOT NULL,
+    `balance` int(11) NOT NULL DEFAULT 0,
+    `paymentamount` int(11) NOT NULL DEFAULT 0,
+    `paymentsleft` int(11) NOT NULL DEFAULT 0,
+    `financetime` int(11) NOT NULL DEFAULT 0,
```
Comment (Manason) [inline migrate.sql]: Why the default values?

File: migrate.sql [hunk 4]
```diff
@@ -0,0 +1,23 @@
+CREATE TABLE IF NOT EXISTS `vehicle_financing` (
+    `id` int(11) NOT NULL AUTO_INCREMENT,
+    `citizenid` varchar(50) DEFAULT NULL,
+    `plate` varchar(15) NOT NULL,
+    `balance` int(11) NOT NULL DEFAULT 0,
+    `paymentamount` int(11) NOT NULL DEFAULT 0,
+    `paymentsleft` int(11) NOT NULL DEFAULT 0,
```
Comment (Manason) [inline migrate.sql]: Do we need to continue to store payments left? Feels like a derived field of the other 3

File: migrate.sql [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+    `id` int(11) NOT NULL AUTO_INCREMENT,
+    `citizenid` varchar(50) DEFAULT NULL,
+    `plate` varchar(15) NOT NULL,
+    `balance` int(11) NOT NULL DEFAULT 0,
+    `paymentamount` int(11) NOT NULL DEFAULT 0,
+    `paymentsleft` int(11) NOT NULL DEFAULT 0,
+    `financetime` int(11) NOT NULL DEFAULT 0,
+    PRIMARY KEY (`id`),
+    FOREIGN KEY `plate` (`plate`) REFERENCES `player_vehicles` (`plate`) ON DELETE CASCADE ON UPDATE CASCADE,
+    FOREIGN KEY `citizenid` (`citizenid`) REFERENCES `players` (citizenid) ON DELETE CASCADE ON UPDATE CASCADE
```
Comment (Manason) [inline migrate.sql]: If we're going to keep this, shouldn't it reference the citizenid on the vehicles table instead?

File: migrate.sql [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+INSERT INTO vehicle_financing (citizenid, plate, balance, paymentamount, paymentsleft, financetime)
+SELECT citizenid, plate, balance, paymentamount, paymentsleft, financetime
+FROM player_vehicles
+WHERE balance > 0 OR paymentamount > 0 OR paymentsleft > 0 OR financetime > 0;
+
+ALTER TABLE player_vehicles
+DROP COLUMN balance,
+DROP COLUMN paymentamount,
+DROP COLUMN paymentsleft,
+DROP COLUMN financetime;
```
Comment (Manason) [inline migrate.sql]: I think we should remove this

**Review by Manason — CHANGES_REQUESTED** [review]
Left comments on the migrate.sql only that apply to all the sql. Haven't reviewed lua yet.

I wouldn't repeat the table creation within the migrate.sql.

I think the best strategy here is to leave the player_vehicles table alone to preserve backwards compatibility, but use this new table in qbx_vehicleshop. That way other vehicle shop resources will continue to work by using the other table

File: migrate.sql (hunk 2 above)
Comment (TonybynMp4) [reply migrate.sql]: No need to get the both financing & vehicle data at the same time,
So it's easier to use citizenId as an id

File: migrate.sql (hunk 3 above)
Comment (TonybynMp4) [reply migrate.sql]: That's how it was🤷🏻‍♂️, didn't want to break anything (we never know), but i'll change it to NULL

**Comment by TonybynMp4** [comment]
> I wouldn't repeat the table creation within the migrate.sql.

migrate.sql should be what people execute if they already had qb / the previous versions of qbx vehicleshop, where import is ONLY used when creating a new server.


> I think the best strategy here is to leave the player_vehicles table alone to preserve backwards compatibility, but use this new table in qbx_vehicleshop. That way other vehicle shop resources will continue to work by using the other table

Other resources should have it's own sql file to add those, and since this change would only affect people that use OUR resource they wouldn't be impacted

File: migrate.sql (hunk 1 above)
Comment (TonybynMp4) [reply migrate.sql]: yeah that's a better idea 👍🏻

File: migrate.sql (hunk 4 above)
Comment (TonybynMp4) [reply migrate.sql]: If you're willing to remove it from the lua why not, i don't want to break it as i can't seem to really understand how the financing system works.

File: migrate.sql (hunk 5 above)
Comment (TonybynMp4) [reply migrate.sql]: The players_vehicles shouldn't even have a citizenid column tbh,
But if i really need to defend this, the citizenid of financing isn't really a reference to the player that owns the vehicle,
it's a reference to the player (character but whatever) that pays for the 'loan'.

File: migrate.sql [hunk 7]
```diff
@@ -0,0 +1,24 @@
+CREATE TABLE IF NOT EXISTS `vehicle_financing` (
+    `vehicleId` int(11) NOT NULL,
+    `citizenid` varchar(50) NOT NULL,
+    `plate` varchar(15) NOT NULL,
```
Comment (Manason) [inline migrate.sql]: We should remove these two and INNER JOIN with player_vehicles? I think we can safely assume that only the owner of the vehicle is the holder of the loan. Otherwise we're duplicating the same data across multiple tables and then using FK to keep it in sync, it seems silly.

File: server/storage.lua [hunk 8]
```diff
@@ -76,13 +70,13 @@ end
...
 function UpdateVehicleEntityFinanceTime(time, plate)
-    MySQL.update('UPDATE player_vehicles SET financetime = ? WHERE plate = ?', {time, plate})
+    MySQL.update('UPDATE vehicle_financing SET financetime = ? WHERE plate = ?', {time, plate})
 end
 
 ---@param vehicleFinance VehicleFinanceServer
 ---@param plate string
 function UpdateVehicleFinance(vehicleFinance, plate)
-    MySQL.update('UPDATE player_vehicles SET balance = ?, paymentamount = ?, paymentsleft = ?, financetime = ? WHERE plate = ?', {
+    MySQL.update('UPDATE vehicle_financing SET balance = ?, paymentamount = ?, paymentsleft = ?, financetime = ? WHERE plate = ?', {
```
Comment (Manason) [inline server/storage.lua]: Can we use vehicle id instead of plate? We should try to get away from using plate as much as possible since it's liable to change and therefore not a great id to use.

File: server/storage.lua [hunk 9]
```diff
@@ -96,12 +90,25 @@ end
...
 ---@return VehicleEntity[]
 function FetchFinancedVehicleEntitiesByCitizenId(citizenId)
-    return MySQL.query.await('SELECT * FROM player_vehicles WHERE citizenid = ? AND balance > 0 AND financetime < 1', {citizenId})
+    return MySQL.query.await('SELECT * FROM vehicle_financing WHERE citizenid = ? AND balance > 0 AND financetime < 1', {citizenId})
+end
+
+---@param license string
+---@return VehicleEntity[]
+function FetchFinancedVehicleEntitiesByLicense(license)
+    return MySQL.query.await('SELECT * FROM vehicle_financing WHERE citizenid IN (SELECT citizenid FROM players WHERE license = ?) AND balance > 0 AND financetime < 1', {license})
```
Comment (Manason) [inline server/storage.lua]: INNER JOINs are preferred over subqueries as they make one pass over the data instead of two.

File: migrate.sql [hunk 10]
```diff
@@ -0,0 +1,24 @@
...
+INSERT INTO vehicle_financing (citizenid, plate, balance, paymentamount, paymentsleft, financetime)
+SELECT citizenid, plate, balance, paymentamount, paymentsleft, financetime
+FROM player_vehicles
+WHERE balance > 0 OR paymentamount > 0 OR paymentsleft > 0 OR financetime > 0;
+
+ALTER TABLE player_vehicles
+DROP COLUMN balance,
+DROP COLUMN paymentamount,
+DROP COLUMN paymentsleft,
+DROP COLUMN financetime;
```
Comment (Manason) [inline migrate.sql:20]: Don't drop columns of player_vehicles. Just don't use them and ignore them.

**Review by Manason — CHANGES_REQUESTED** [review]

File: migrate.sql (hunk 5 above)
Comment (Manason) [reply migrate.sql]: I'm confused why you say the player_vehicles shouldn't have citizenid? Doesn't a vehicle need to be associated to a player?

File: migrate.sql (hunk 10 above)
Comment (TonybynMp4) [reply migrate.sql:20]: Why keep things we don't use? the whole point of migrating is to *move* these somewhere else

File: server/storage.lua (hunk 8 above)
Comment (TonybynMp4) [reply server/storage.lua]: I'll change everything over to vehicle id 👍🏻

File: migrate.sql (hunk 7 above)
Comment (TonybynMp4) [reply migrate.sql]: true, i'll change the queries to make that work.

File: migrate.sql (hunk 5 above)
Comment (TonybynMp4) [reply migrate.sql]: Don't worry about it, i think vehicles should be separated from players but that's for another time.

File: migrate.sql (hunk 10 above)
Comment (Manason) [reply migrate.sql:20]: On second thought, I think it's fine.

File: server/main.lua [hunk 11]
```diff
@@ -318,7 +325,7 @@ local function sellShowroomVehicleTransact(src, target, price, downPayment)
     player.Functions.AddMoney('bank', price * config.commissionRate)
     exports.qbx_core:Notify(src, locale('success.earned_commission', lib.math.groupdigits(commission)), 'success')
 
-    exports['Renewed-Banking']:addAccountMoney(player.PlayerData.job.name, price)
+    exports.qbx_management:AddMoney(player.PlayerData.job.name, price)
```
Comment (Manason) [inline server/main.lua]: Is this a real export?

File: server/storage.lua [hunk 12]
```diff
@@ -6,7 +6,7 @@
 
 ---@param request InsertVehicleEntityRequest
 function InsertVehicleEntity(request)
-    MySQL.insert('INSERT INTO player_vehicles (license, citizenid, vehicle, hash, mods, plate, garage, state) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', {
+    local vehicleId = MySQL.insert.await('INSERT INTO player_vehicles (license, citizenid, vehicle, hash, mods, plate, garage, state) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', {
```
Comment (Manason) [inline server/storage.lua]: Shouldn't we be calling qbx_vehicles API for this instead?

File: server/storage.lua [hunk 13]
```diff
@@ -93,18 +94,30 @@ end
...
+function FetchFinancedVehicleEntityById(id)
+    return MySQL.single.await('SELECT * FROM vehicle_financing WHERE vehicleId = ? AND balance > 0 AND financetime < 1', {id})
 end
 
 ---@param citizenId string
----@return VehicleEntity[]
+---@return VehicleFinancingEntity
 function FetchFinancedVehicleEntitiesByCitizenId(citizenId)
-    return MySQL.query.await('SELECT * FROM player_vehicles WHERE citizenid = ? AND balance > 0 AND financetime < 1', {citizenId})
+    return MySQL.query.await('SELECT vehicle_financing.* FROM vehicle_financing INNER JOIN player_vehicles ON player_vehicles.citizenid = "KLH31301" WHERE vehicle_financing.vehicleId = player_vehicles.id AND vehicle_financing.balance > 0 AND vehicle_financing.financetime > 1', {citizenId})
```
Comment (Manason) [inline server/storage.lua]: Looks like test code?

File: server/storage.lua [hunk 14]
```diff
@@ -93,18 +94,30 @@ end
...
 end
 
----@param plate string
-function DeleteVehicleEntity(plate)
-    MySQL.query('DELETE FROM player_vehicles WHERE plate = ?', {plate})
+---@param license string
+---@return VehicleFinancingEntity
+function FetchFinancedVehicleEntitiesByLicense(license)
+    return MySQL.query.await('SELECT * FROM vehicle_financing AS vf INNER JOIN players AS p ON p.citizenid = ? INNER JOIN player_vehicles AS pv ON pv.citizenid = p.citizenid AND vf.balance > 0 AND vf.financetime < 1', {license})
```
Comment (Manason) [inline server/storage.lua]: What columns do we take from the player table?

File: server/storage.lua [hunk 15]
```diff
@@ -93,18 +94,30 @@ end
...
 end
+
+---@param vehicleId integer
+function DeleteVehicleEntity(vehicleId)
+    MySQL.query('DELETE FROM player_vehicles WHERE id = ?', {vehicleId})
+end
```
Comment (Manason) [inline server/storage.lua]: This should call qbx_vehicles API, no?

File: vehshop.sql [hunk 16]
```diff
@@ -1,38 +1,9 @@
...
-ADD COLUMN `paymentamount` int(11) NOT NULL DEFAULT 0;
-ALTER TABLE `player_vehicles`
-ADD COLUMN `paymentsleft` int(11) NOT NULL DEFAULT 0;
-ALTER TABLE `player_vehicles`
-ADD COLUMN `financetime` int(11) NOT NULL DEFAULT 0;
+CREATE TABLE IF NOT EXISTS `vehicle_financing` (
+    `vehicleId` int(11) NOT NULL,
+    `balance` int(11) DEFAULT NULL,
+    `paymentamount` int(11) DEFAULT NULL,
+    `paymentsleft` int(11) DEFAULT NULL,
```
Comment (Manason) [inline vehshop.sql:5]: We should remove payments left. Doesn't have to be done in this PR though.

**Review by Manason — CHANGES_REQUESTED** [review]

File: server/main.lua (hunk 11 above)
Comment (TonybynMp4) [reply server/main.lua]: How the hell did this get here 😆

File: server/storage.lua (hunk 12 above)
Comment (TonybynMp4) [reply server/storage.lua]: I'll have to modify the API

File: server/storage.lua (hunk 13 above)
Comment (TonybynMp4) [reply server/storage.lua]: It is.

File: server/storage.lua (hunk 15 above)
Comment (TonybynMp4) [reply server/storage.lua]: again, gotta modify the API

File: server/storage.lua (hunk 14 above)
Comment (TonybynMp4) [reply server/storage.lua]: citizenId

File: server/storage.lua [hunk 17]
```diff
@@ -6,16 +6,13 @@
...
-        request.plate,
-        'pillboxgarage',
-        0
+    exports.qbx_vehicles:CreateVehicleEntity({
+        citizenId = request.citizenId,
+        model = request.model,
+        plate = request.plate,
+        state = 0
     })
+    return vehicleId
```
Comment (Manason) [inline server/storage.lua]: Where does this variable come from? Also InsertVehicleEntity doesn't seem like it needs to exist only as a wrapper of CreateVehicleEntity. Consider moving CreateVehicleEntity in-line.

File: server/storage.lua (hunk 14 above)
Comment (Manason) [reply server/storage.lua]: Consider limiting the selection to avoid unnecessary columns reads

**Review by Manason — CHANGES_REQUESTED** [review]

File: server/storage.lua (hunk 17 above)
Comment (TonybynMp4) [reply server/storage.lua]: woopsies, idk about moving the export directly in main.lua, feels like storage is kinda made for this 🤔

File: server/storage.lua (hunk 14 above)
Comment (TonybynMp4) [reply server/storage.lua]: Already did.

File: server/storage.lua (hunk 17 above)
Comment (Manason) [reply server/storage.lua]: It's an unneeded abstraction, no? The same data passed two levels down? Doesn't feel like this function is doing any additional work.

**Review by Manason — APPROVED** [review]

File: migrate.sql [hunk 18]
```diff
@@ -0,0 +1,20 @@
+CREATE TABLE IF NOT EXISTS `vehicle_financing` (
+    `vehicleId` int(11) NOT NULL,
+    `balance` int(11) DEFAULT NULL,
+    `paymentamount` int(11) DEFAULT NULL,
+    `paymentsleft` int(11) DEFAULT NULL,
```
Comment (FjamZoo) [inline migrate.sql]: We could probably switch this to tinyint as paymentsleft would never go above 255

**Review by FjamZoo — CHANGES_REQUESTED** [review]

File: migrate.sql (hunk 18 above)
Comment (TonybynMp4) [reply migrate.sql]: It should be alright yeah, but if it breaks anything i'll blame you! 😆

**Review by Manason — APPROVED** [review]

**Review by mafewtm — APPROVED** [review]
